# Generated by Django 5.1.1 on 2025-01-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('datasets', '0004_remove_datasets_workplace_datasets_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('config', models.JSONField()),
                ('model_file', models.FileField(upload_to='config/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.datasets')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workspace')),
            ],
        ),
    ]
