# Generated by Django 5.1.1 on 2025-01-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='exp_file',
            field=models.FileField(default=1, upload_to='config/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_file',
            field=models.FileField(upload_to='models/'),
        ),
    ]
