# Generated by Django 5.1.1 on 2025-01-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0002_mlmodel_exp_file_alter_mlmodel_model_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodel',
            old_name='config',
            new_name='exp_config',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='model_param',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
