# Generated by Django 5.1.1 on 2025-01-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0003_rename_config_mlmodel_exp_config_mlmodel_model_param'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='exp_config',
        ),
    ]
