# Generated by Django 5.1.1 on 2025-02-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('datasets', '0004_remove_datasets_workplace_datasets_workspace_and_more'),
        ('mlapp', '0006_mlmodel_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModelProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=1)),
                ('is_target', models.CharField(blank=True, max_length=10, null=True)),
                ('data_target', models.CharField(blank=True, max_length=255, null=True)),
                ('columns_type', models.CharField(blank=True, max_length=50, null=True)),
                ('preprocessing_steps', models.JSONField(blank=True, null=True)),
                ('model_type', models.CharField(blank=True, max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('hyperparameters', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.datasets')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workspace')),
            ],
        ),
    ]
